[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.26.0"
colored = "2.0.0"
text_io = "0.1.9"
crossterm = "0.23.0"
termion = "1.5.6"
